#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication_token:
    path: /auth/login
    methods: ['POST']

refresh_token:
    path:     /auth/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
